services:
  - type: web
    name: pulsetrack-backend
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.server.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: SUPABASE_BUCKET
        value: pulse
      - key: SUPABASE_OBJECT_PATH
        value: snapstats/nigeria_states.geojson
      - key: UPLOAD_DIR
        value: /var/data/uploads
    healthCheckPath: /healthz

