name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/render-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "No Render deploy hook configured" && exit 0
          fi
          curl -sSf -X POST "$RENDER_DEPLOY_HOOK"

